{
 "title": "Prometheus JMX exporter for Kubernetes",
 "description": "After selecting your namespace and container you get a wealth of JVM based metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container!=\"POD\"},namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used (relative to request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum((jvm_memory_bytes_used{service=\"$container\", namespace=\"$namespace\", area=\"heap\"})) / sum((jvm_memory_bytes_max{area=\"heap\",service=\"$container\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{service=\"$container\", namespace=\"$namespace\", area=\"heap\"}) / count(jvm_memory_bytes_max{service=\"$container\", namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "Max limit"
    },
    {
     "expr": "jvm_memory_bytes_used{service=\"$container\", namespace=\"$namespace\", area=\"heap\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{service=\"$container\", namespace=\"$namespace\", area=\"nonheap\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time increase (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{service=\"$container\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count increase (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{service=\"$container\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time (average per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{service=\"$container\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{gc}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$container\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$container\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$container\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$container\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$container\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$container\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\", service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\", service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "JVM current threads   {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "JVM daemon threads  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "JVM deadlocked threads  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Class Loading (average per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{service=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "loaded  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Par Eden Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$container\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$container\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$container\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CMS Old Gen (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$container\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$container\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$container\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Par Survivor Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{service=\"$container\", namespace=\"$namespace\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{service=\"$container\", namespace=\"$namespace\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{service=\"$container\", namespace=\"$namespace\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}