apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_jmx.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.label }}
spec:
  selector:
    app: {{ .Values.pod.label }}
  ports:
    - port: {{ .Values.service_jmx.port }}
      targetPort: {{ .Values.service_jmx.targetPort }}
      nodePort: {{ .Values.service_jmx.nodePort}}
  type: {{ .Values.service_jmx.type }}